import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { COMMON_RULES, RULE_PACKS, packsForStack } from "./rules-catalog.mjs";
import {
  DEFAULT_RULE_TARGETS,
  RULE_TARGETS,
  describeRuleCatalog,
  installProjectRules,
  planRuleFiles,
  renderAgentsRulesSection,
  renderClaudeMdSection,
  renderClaudeRules,
  renderCursorRules,
  replaceMarkdownSection
} from "./rules-library.mjs";

test("catalog is well formed and stack mapping is additive", () => {
  assert.ok(COMMON_RULES.length >= 5);
  for (const rule of COMMON_RULES) assert.match(rule.content, /^# /);
  for (const pack of RULE_PACKS) {
    assert.ok(pack.paths.length > 0, pack.id);
    assert.ok(pack.stacks.length > 0, pack.id);
    assert.doesNotMatch(pack.content, /\b(TODO|TBD|FIXME)\b/);
  }
  assert.deepEqual(packsForStack(["Node.js", "TypeScript", "Next.js", "React", "Tailwind CSS", "Docker"]), ["typescript", "react", "web", "docker"]);
  assert.deepEqual(packsForStack(["Node.js"]), ["typescript"]);
  assert.deepEqual(packsForStack(["Python", "FastAPI"]), ["python", "fastapi"]);
  assert.deepEqual(packsForStack(["Vue"], ["frontend"]), ["vue", "web"]);
  assert.deepEqual(packsForStack([], ["frontend"]), ["web"]);
  assert.deepEqual(packsForStack(["Go", "Rust", "Java/JVM"]), ["golang", "rust", "java"]);
  assert.deepEqual(packsForStack(["Java/JVM", "Kotlin"]), ["java", "kotlin"]);
  assert.deepEqual(packsForStack(["Node.js", "React", "React Native/Expo"]), ["typescript", "react", "react-native"],
    "a React Native app gets no web rules: there is no DOM");
  assert.deepEqual(packsForStack(["PHP", "Laravel"]), ["php"]);
  // Д-18: the two packs that had no detector label until the root directory was
  // listed. ArkTS is deliberately still without one — see the debt entry.
  assert.deepEqual(packsForStack(["Perl"]), ["perl"]);
  assert.deepEqual(packsForStack(["F#"]), ["fsharp"]);
  assert.deepEqual(packsForStack(["C#/.NET", "F#"]), ["csharp", "fsharp"]);
  assert.deepEqual(packsForStack(["ArkTS/HarmonyOS"]), [], "the detector labels ArkTS; no pack claims it yet");
  // Every pack is reachable from a stack label the detector can produce, or it
  // is only ever installed by name.
  const detected = new Set(["TypeScript", "React", "Vue", "Angular", "React Native/Expo", "Tailwind CSS", "Python", "FastAPI",
    "Go", "Rust", "Java/JVM", "Kotlin", "Swift", "Flutter/Dart", "C#/.NET", "C/C++", "PHP", "Ruby", "Perl", "F#", "Docker"]);
  for (const pack of RULE_PACKS) {
    assert.ok(pack.stacks.some((label) => detected.has(label)), `${pack.id} names no detectable stack`);
  }
  const catalog = describeRuleCatalog();
  assert.equal(catalog.packs.length, RULE_PACKS.length);
});

test("projections carry the right frontmatter for Claude Code and Cursor", () => {
  const claude = renderClaudeRules(["typescript"]);
  const common = claude.find((file) => file.path.endsWith("common-coding-style.md"));
  assert.match(common.content, /^<!-- generated by ai-dev-system/);
  const pack = claude.find((file) => file.path.endsWith("/typescript.md"));
  assert.match(pack.content, /^---\npaths: \["\*\*\/\*\.ts"/);
  assert.match(pack.content, /\n---\n\n<!-- generated by ai-dev-system/);
  const cursor = renderCursorRules(["python"]);
  assert.match(cursor.find((file) => file.path.endsWith("ai-dev-python.mdc")).content, /globs: \["\*\*\/\*\.py", "\*\*\/\*\.pyi"\]\nalwaysApply: false/);
  assert.match(cursor.find((file) => file.path.endsWith("ai-dev-common-security.mdc")).content, /alwaysApply: true/);
  const section = renderAgentsRulesSection(["typescript", "web"]);
  assert.match(section, /^## Engineering Rules/);
  assert.match(section, /TypeScript \/ JavaScript: `\.ai-dev\/rules\/typescript\.md`/);
  assert.throws(() => planRuleFiles({ packIds: ["cobol"] }), /Unknown rule pack: cobol/);
  assert.throws(() => planRuleFiles({ packIds: [], targets: ["vim"] }), /Unknown rules target: vim/);
});

test("replaceMarkdownSection replaces in place or appends", () => {
  const original = "# AGENTS.md\n\n## Project\n\n- Name: x\n\n## Engineering Rules\n\nold\n\n## Skill Routing\n\n- feature\n";
  const next = replaceMarkdownSection(original, "## Engineering Rules", "## Engineering Rules\n\nnew body");
  assert.equal(next, "# AGENTS.md\n\n## Project\n\n- Name: x\n\n## Engineering Rules\n\nnew body\n\n## Skill Routing\n\n- feature\n");
  assert.equal(replaceMarkdownSection("", "## Engineering Rules", "## Engineering Rules\n\nbody"), "## Engineering Rules\n\nbody\n");
  assert.equal(replaceMarkdownSection("# A\n", "## Engineering Rules", "## Engineering Rules\n\nbody"), "# A\n\n## Engineering Rules\n\nbody\n");
});

test("installProjectRules writes canonical files and projections, respects existing files, and is idempotent", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "rules-library-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.writeFile(path.join(root, "AGENTS.md"), "# AGENTS.md\n\n## Project\n\n- Name: fixture\n");

  const dry = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript", "React"], dryRun: true });
  assert.deepEqual(dry.packs, ["typescript", "react", "web"]);
  assert.ok(dry.planned.includes(".ai-dev/rules/common/coding-style.md"));
  assert.ok(dry.planned.includes("AGENTS.md"));
  assert.equal(await fs.access(path.join(root, ".ai-dev")).then(() => true).catch(() => false), false);

  const first = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript", "React"] });
  assert.ok(first.written.includes(".ai-dev/rules/typescript.md"));
  assert.ok(first.written.includes(".claude/rules/ai-dev/common-testing.md"));
  assert.ok(first.written.includes(".cursor/rules/ai-dev-react.mdc"));
  assert.ok(first.updated.includes("AGENTS.md"));
  const agents = await fs.readFile(path.join(root, "AGENTS.md"), "utf8");
  assert.match(agents, /## Engineering Rules/);
  assert.match(agents, /- Name: fixture/);

  const second = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript", "React"] });
  assert.equal(second.written.length, 0);
  assert.equal(second.updated.length, 0);
  assert.ok(second.skipped.length > 0);

  await fs.writeFile(path.join(root, ".ai-dev", "rules", "typescript.md"), "# my custom typescript rules\n");
  const third = await installProjectRules({ projectRoot: root, packs: ["typescript"], targets: ["ai-dev"] });
  assert.ok(third.skipped.some((item) => item.startsWith(".ai-dev/rules/typescript.md (exists")));
  assert.equal(await fs.readFile(path.join(root, ".ai-dev", "rules", "typescript.md"), "utf8"), "# my custom typescript rules\n");
  const forced = await installProjectRules({ projectRoot: root, packs: ["typescript"], targets: ["ai-dev"], overwrite: true });
  assert.ok(forced.updated.includes(".ai-dev/rules/typescript.md"));
});

test("the claude-md target imports the common rules into CLAUDE.md instead of copying them", async (t) => {
  const section = renderClaudeMdSection(["typescript"]);
  assert.match(section, /^## Engineering Rules/);
  // Claude Code expands `@path` at startup and resolves a path, not a glob:
  // one import line per common rule file, and no `@` for the path-scoped packs.
  for (const rule of COMMON_RULES) {
    assert.ok(section.includes(`@.ai-dev/rules/common/${rule.id}.md`), `missing import for ${rule.id}`);
  }
  assert.equal(section.includes("@.ai-dev/rules/common/*.md"), false);
  assert.match(section, /- TypeScript \/ JavaScript: `\.ai-dev\/rules\/typescript\.md`/);
  assert.equal(/^@.*typescript\.md/m.test(section), false, "path-scoped packs are referenced, not imported");
  assert.doesNotMatch(renderClaudeMdSection([]), /Language packs/);

  assert.ok(RULE_TARGETS.includes("claude-md"));
  assert.equal(DEFAULT_RULE_TARGETS.includes("claude-md"), false, "claude-md replaces the claude target, so it is opt-in");
  assert.deepEqual(
    planRuleFiles({ packIds: [], targets: ["claude-md"] }).map((file) => file.path),
    ["CLAUDE.md"]
  );

  const root = await fs.mkdtemp(path.join(os.tmpdir(), "rules-claude-md-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.writeFile(path.join(root, "CLAUDE.md"), "# Project\n\n## Build\n\n- npm test\n");

  const first = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript"], targets: ["ai-dev", "claude-md"] });
  assert.ok(first.updated.includes("CLAUDE.md"));
  assert.equal(first.written.some((item) => item.startsWith(".claude/")), false, "nothing is copied into .claude/rules");
  const claudeMd = await fs.readFile(path.join(root, "CLAUDE.md"), "utf8");
  assert.match(claudeMd, /# Project\n\n## Build\n\n- npm test/, "hand-written content is kept");
  assert.match(claudeMd, /## Engineering Rules\n\n<!-- generated by ai-dev-system/);
  assert.match(claudeMd, /@\.ai-dev\/rules\/common\/security\.md/);
  for (const rule of COMMON_RULES) {
    assert.ok(await fs.readFile(path.join(root, ".ai-dev", "rules", "common", `${rule.id}.md`), "utf8"));
  }

  const second = await installProjectRules({ projectRoot: root, stack: ["Node.js", "TypeScript"], targets: ["ai-dev", "claude-md"] });
  assert.equal(second.updated.length + second.written.length, 0, "second install is a no-op");
  assert.ok(second.skipped.includes("CLAUDE.md (section current)"));

  // A CLAUDE.md that does not exist yet is created with just the section.
  const fresh = await fs.mkdtemp(path.join(os.tmpdir(), "rules-claude-md-new-"));
  t.after(() => fs.rm(fresh, { recursive: true, force: true }));
  const created = await installProjectRules({ projectRoot: fresh, packs: [], targets: ["claude-md"] });
  assert.deepEqual(created.written, ["CLAUDE.md"]);
  assert.match(await fs.readFile(path.join(fresh, "CLAUDE.md"), "utf8"), /^## Engineering Rules/);
});
